"""initial schema

Revision ID: b057596f7ee2
Revises: 
Create Date: 2026-04-30 15:05:40.205309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b057596f7ee2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('recording_id', sa.String(), nullable=True),
    sa.Column('transcript_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sub_code', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('transcript_path', sa.String(), nullable=True),
    sa.Column('recording_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_bot_id'), 'meetings', ['bot_id'], unique=True)
    op.create_index(op.f('ix_meetings_recording_id'), 'meetings', ['recording_id'], unique=False)
    op.create_index(op.f('ix_meetings_transcript_id'), 'meetings', ['transcript_id'], unique=False)
    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_log_bot_id'), 'webhook_log', ['bot_id'], unique=False)
    op.create_index('uq_wh_event', 'webhook_log', ['event_id'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('recall_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('speaker_label', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segments_meeting_start', 'transcript_segments', ['meeting_id', 'start_ms'], unique=False)
    op.execute(
        """
        CREATE VIRTUAL TABLE segments_fts USING fts5(
            text, speaker_label,
            meeting_id UNINDEXED,
            segment_id UNINDEXED,
            tokenize = 'porter unicode61'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_fts_ai AFTER INSERT ON transcript_segments BEGIN
            INSERT INTO segments_fts(rowid, text, speaker_label, meeting_id, segment_id)
            VALUES (new.id, new.text, new.speaker_label, new.meeting_id, new.id);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_fts_ad AFTER DELETE ON transcript_segments BEGIN
            INSERT INTO segments_fts(segments_fts, rowid, text, speaker_label, meeting_id, segment_id)
            VALUES ('delete', old.id, old.text, old.speaker_label, old.meeting_id, old.id);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER segments_fts_au AFTER UPDATE ON transcript_segments BEGIN
            INSERT INTO segments_fts(segments_fts, rowid, text, speaker_label, meeting_id, segment_id)
            VALUES ('delete', old.id, old.text, old.speaker_label, old.meeting_id, old.id);
            INSERT INTO segments_fts(rowid, text, speaker_label, meeting_id, segment_id)
            VALUES (new.id, new.text, new.speaker_label, new.meeting_id, new.id);
        END
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS segments_fts_au")
    op.execute("DROP TRIGGER IF EXISTS segments_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS segments_fts_ai")
    op.execute("DROP TABLE IF EXISTS segments_fts")
    op.drop_index('ix_segments_meeting_start', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_table('participants')
    op.drop_index('uq_wh_event', table_name='webhook_log')
    op.drop_index(op.f('ix_webhook_log_bot_id'), table_name='webhook_log')
    op.drop_table('webhook_log')
    op.drop_index(op.f('ix_meetings_transcript_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_recording_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_bot_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
